'use client';

import { useEffect, useRef } from 'react';
import { X } from 'lucide-react';

interface SandboxedGameProps {
    htmlContent: string;
    onClose: () => void;
}

export function SandboxedGame({ htmlContent, onClose }: SandboxedGameProps) {
    const iframeRef = useRef<HTMLIFrameElement>(null);

    useEffect(() => {
        if (iframeRef.current) {
            const iframe = iframeRef.current;
            const doc = iframe.contentDocument || iframe.contentWindow?.document;

            if (doc) {
                doc.open();
                doc.write(htmlContent);
                doc.close();
            }
        }
    }, [htmlContent]);

    return (
        <div className="fixed inset-0 bg-black/80 z-50 flex items-center justify-center p-4">
            <div className="bg-white rounded-2xl w-full max-w-4xl h-[80vh] flex flex-col shadow-2xl">
                {/* Header */}
                <div className="flex items-center justify-between p-4 border-b border-slate-200">
                    <h3 className="text-lg font-semibold text-slate-800">Custom Game</h3>
                    <button
                        onClick={onClose}
                        className="p-2 hover:bg-slate-100 rounded-lg transition-colors"
                    >
                        <X className="w-5 h-5" />
                    </button>
                </div>

                {/* Game Container */}
                <div className="flex-1 overflow-hidden">
                    <iframe
                        ref={iframeRef}
                        sandbox="allow-scripts"
                        className="w-full h-full border-0"
                        title="Custom Educational Game"
                    />
                </div>

                {/* Footer */}
                <div className="p-3 border-t border-slate-200 bg-slate-50 text-center">
                    <p className="text-xs text-slate-500">
                        🎮 Game generated by Adeline • Safe sandboxed environment
                    </p>
                </div>
            </div>
        </div>
    );
}
